"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { diagnoseIncident, DiagnoseResponse } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { BrainCircuit, CheckCircle2, AlertCircle, ArrowLeft, Lightbulb, History, ShieldAlert, Activity } from "lucide-react";

export default function DiagnosePage() {
  const params = useParams();
  const router = useRouter();
  const [diagnosis, setDiagnosis] = useState<DiagnoseResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (params.id) {
      diagnoseIncident(params.id as string)
        .then(data => setDiagnosis(data))
        .catch(err => setError(err.message))
        .finally(() => setLoading(false));
    }
  }, [params.id]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] space-y-6">
        <div className="relative flex items-center justify-center">
          <div className="absolute animate-ping w-24 h-24 rounded-full border-4 border-primary opacity-20"></div>
          <div className="absolute animate-spin w-16 h-16 rounded-full border-t-4 border-b-4 border-primary"></div>
          <BrainCircuit className="w-8 h-8 text-primary relative z-10" />
        </div>
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-bold tracking-tight text-foreground">AI is analyzing logs & memories...</h2>
          <p className="text-muted-foreground text-sm">Querying Hindsight vector database for similar past incidents...</p>
        </div>
      </div>
    );
  }

  if (error) return <div className="p-8 text-center text-destructive">Error: {error}</div>;
  if (!diagnosis) return null;

  const confidencePercentage = Math.round(diagnosis.confidence_score || 0);

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center space-x-4">
        <button onClick={() => router.back()} className="p-2 hover:bg-secondary rounded-full transition-colors">
          <ArrowLeft className="w-5 h-5 text-muted-foreground" />
        </button>
        <div>
          <h1 className="text-3xl font-bold tracking-tight">AI Diagnosis Results</h1>
          <p className="text-muted-foreground mt-1">Generated by Groq & Vectorize.io Hindsight</p>
        </div>
      </div>

      <Card className="border-primary/20 shadow-lg shadow-primary/5">
        <CardHeader className="pb-4">
          <CardTitle className="flex items-center text-2xl">
            <CheckCircle2 className="w-6 h-6 mr-3 text-primary" />
            Root Causes Ranking
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {diagnosis.root_causes?.map((cause, i) => (
              <div key={i} className="p-4 bg-secondary/50 rounded-lg border border-border flex items-start">
                <div className="mr-4 mt-0.5 flex-shrink-0 w-6 h-6 rounded-full bg-primary/20 text-primary flex items-center justify-center text-sm font-bold">
                  {i + 1}
                </div>
                <p className="text-lg font-medium">{cause}</p>
              </div>
            ))}
          </div>
          
          <div className="mt-6">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-muted-foreground">Combined Confidence Score (AI + Semantic Memory)</span>
              <span className="text-sm font-bold text-primary">{confidencePercentage}/100</span>
            </div>
            <Progress value={confidencePercentage} className="h-3" />
          </div>
        </CardContent>
      </Card>

      <Card className="border-primary/10 shadow-md">
        <CardHeader>
          <CardTitle className="flex items-center text-xl">
            <Activity className="w-5 h-5 mr-3 text-blue-500" />
            Impact Analysis
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed">{diagnosis.impact_analysis}</p>
        </CardContent>
      </Card>

      <div className="grid md:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <Lightbulb className="w-5 h-5 mr-2 text-yellow-500" />
              Recommended Actions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {diagnosis.recommended_actions?.map((action, i) => (
                <li key={i} className="flex items-start">
                  <div className="mr-3 mt-0.5 flex-shrink-0 w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center text-xs font-bold">
                    {i + 1}
                  </div>
                  <span className="text-sm leading-relaxed">{action}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <ShieldAlert className="w-5 h-5 mr-2 text-green-500" />
              Prevention Steps
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {diagnosis.prevention_steps?.map((step, i) => (
                <li key={i} className="flex items-start">
                  <div className="mr-3 mt-0.5 flex-shrink-0 w-5 h-5 rounded-full bg-green-500/20 text-green-600 flex items-center justify-center text-xs font-bold">
                    {i + 1}
                  </div>
                  <span className="text-sm leading-relaxed">{step}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <History className="w-5 h-5 mr-2 text-blue-500" />
              Hindsight Memory
            </CardTitle>
            <CardDescription>Similar past incidents used</CardDescription>
          </CardHeader>
          <CardContent>
            {diagnosis.investigation_mode ? (
              <div className="p-4 border border-dashed rounded-lg text-center text-muted-foreground">
                <AlertCircle className="w-6 h-6 mx-auto mb-2 opacity-50" />
                <p className="text-sm">No similar incidents found in memory. AI is performing a zero-shot diagnosis.</p>
              </div>
            ) : (
              <ul className="space-y-4">
                {diagnosis.similar_incidents?.map((sim, i) => (
                  <li key={i} className="p-4 bg-secondary/30 rounded-lg border border-border text-sm flex flex-col space-y-2">
                    <div className="flex justify-between items-start">
                      <span className="font-semibold text-foreground truncate mr-2">{sim.title}</span>
                      <span className="text-xs font-bold px-2 py-1 bg-primary/20 text-primary rounded whitespace-nowrap">
                        {Math.round(sim.similarity_score * 100)}% Match
                      </span>
                    </div>
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground"><strong className="text-foreground">Root Cause:</strong> {sim.root_cause}</p>
                      <p className="text-xs text-muted-foreground"><strong className="text-foreground">Resolution:</strong> {sim.resolution}</p>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      <div className="flex justify-end pt-4">
        <Link href={`/incidents/${params.id}/resolve`} className="bg-green-600 text-white hover:bg-green-700 h-10 px-8 py-2 inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors shadow-lg shadow-green-600/20">
          Proceed to Resolution
        </Link>
      </div>
    </div>
  );
}
